#!/bin/sh

function age() {
   local filename=$1
   local changed=`stat -c %Y "$filename"`
   local now=`date +%s`
   local elapsed

   let elapsed=now-changed
   echo $elapsed
}


lockfile="/tmp/_securexinetd"


if [ -e $file ]; then
        if [ $(age "$file") -gt "600" ]; then
                echo "Lock file is too old"
        else
                echo "Lock file found, exiting";
                exit;
        fi
fi

touch $lockfile

for file in klogin eklogin ekrb5-telnet gssftp krb5-telnet kshell rsync; do
	if [ -e /etc/xinetd.d/$file ]; then
		echo "  Cleaning $file"
        	/bin/rm /etc/xinetd.d/$file
	fi
done



cd /etc/xinetd.d/
for i in *; do
	if [ -f $i ]; then
		#echo $i
		detainthinks=`cat /etc/xinetd.d/$i  | grep port | awk '{print $3}'`;
		virshknows=`virsh dumpxml $i | grep vnc | grep port | cut -d\' -f4`;
		if [ "$virshknows" = "" ]; then
			virshknows="$(virsh dumpxml $name | grep spice |grep port= | cut -d\' -f4)"
		fi

		if [ "$detainthinks" = "$virshknows" ]; then
			echo "$i is good"
		else
			echo "$i is incorrect, fixing"
			/bin/rm /etc/xinetd.d/$i
		fi

	 fi
done

/bin/rm -v $lockfile
