#!/bin/bash

# exit on lock
if [ -f /dev/shm/lock ]; then
	exit;
	fi

lockfile="/tmp/_securexinetd"


if [ -e $lockfile ]; then
        if [ "$(( $(date +"%s") - $(stat -c "%Y" $lockfile) ))" -gt "300" ]; then
                echo "$lockfile older than 300 seconds";
        else
                echo "ERROR: Lock file found, exiting";
                exit;
        fi
fi

touch $lockfile

for file in klogin eklogin ekrb5-telnet gssftp krb5-telnet kshell rsync; do
	if [ -e /etc/xinetd.d/$file ]; then
		echo "  Cleaning $file"
        	/bin/rm /etc/xinetd.d/$file
	fi
done



cd /etc/xinetd.d/
for i in *; do
	if [ -f $i ]; then
		#echo $i
		detainthinks=`cat /etc/xinetd.d/$i  | grep port | awk '{print $3}'`;
		virshknows=`virsh dumpxml $i 2>/dev/null | grep vnc | grep port | cut -d\' -f4`;
		if [ -z "$virshknows" ]; then
			echo "$i not a vps, skipping"
		elif [ "$detainthinks" = "$virshknows" ]; then
			echo "$i is good"
		else
			echo "$i is incorrect, fixing"
			/bin/rm /etc/xinetd.d/$i
		fi

	 fi
done

if [ -d /etc/debian_version ]; then
	service xinetd restart
elif [ -d /etc/redhat-release ]; then
	if [ -e /usr/bin/systemctl ]; then
		/usr/bin/systemctl restart xinetd.service
	else
		service xinetd restart
	fi
fi

/bin/rm -v $lockfile
