#!/bin/sh
svn update --force --accept theirs-full --username vpsclient --password interserver123 --non-interactive /root/cpaneldirect || rsync -av rsync://vpsadmin.interserver.net/vps/cpaneldirect/ /root/cpaneldirect/;
/admin/upscripts
